### ISSUE TITLE
How to return bool instead of GraphNode

### ISSUE THREAD

**Issue by sakura970** [liumy2010/LiteEFG#5]
hello, mingyang,

I am very interested in your project, I am implementing smooth RM+, but I don't know how to compare GraphNode and float, such as

```
a = LiteEFG.sum(LiteEFG.maximum(self.regret_buffer + gradient - ev, 0.0))
a<=1.0
```

always returns GraphNode instead of bool, how to solve this problem?

**Comment by liumy2010** [comment]
LiteEFG is based on the computation graph so that the code scripts in __init__() are **defining** the graph instead of doing computation. Therefore, a<=1.0 will return a GraphNode with its value equal to a<=1.0.

**Comment by sakura970** [comment]
Thanks for your reply. How do I implement smooth RM+ in this case? I find that I cannot get the value of the GraphNode.

**Comment by liumy2010** [comment]
I guess you are referring to stable Predictive RM. To implement 
```pseudocode
if regret(a)<=1
    regret(a)=1
```
you may use `LiteEFG.maximum(regret, 1.0)`.

**Comment by sakura970** [comment]
No, I am referring to smooth Predictive RM+.  I have to determine whether 
```
a = LiteEFG.sum(LiteEFG.maximum(self.regret_buffer + gradient - ev, 0.0))
```
is less than 1 or greater than 1 to decide whether to use 
```
self.regret_buffer.inplace(LiteEFG.maximum(self.regret_buffer + gradient - ev, 0))
```
or
```
self.regret_buffer.inplace(self.regret_buffer + gradient - ev)
self.regret_buffer.project(distance="L2")
```

**Comment by sakura970** [comment]
Additionally, to my knowladege, to implement stable Predictive RM+, we have to implement
```
if \sum_{a} regret(a)<=1:
    regret(a) = 1/(\sum_{a} 1 )
```
Therefore, you code ``LiteEFG.maximum(regret, 1.0)`` cannot be used to implement stable Predictive RM+.

**Comment by liumy2010** [comment]
Got it. You may try to do this for smooth Predictive RM+
```python
            flg = LiteEFG.sum(LiteEFG.maximum(self.regret_buffer, 0.0)) >= 1.0
            self.flg_true = LiteEFG.maximum(self.regret_buffer, 0.0)
            self.flg_false = LiteEFG.project(self.regret_buffer, distance="L2")
            self.regret_buffer.inplace(self.flg_true * flg + self.flg_false * (1.0 - flg))
```
You may also use the same trick to implement stable Predictive RM+.

**Comment by sakura970** [comment]
Thank you very much for your reply
