### ISSUE TITLE
Non-Synchronized Updates with LiteEFG?

### ISSUE THREAD

**Issue by nanomena** [liumy2010/LiteEFG#8]
I wonder how I can use LiteEFG to implement an algorithm where the epoch updates are not homogeneous. For example, I want to implement an algorithm that has a pivot point updated every 100 epochs.

**Comment by liumy2010** [comment]
LiteEFG supports coloring different parts of the computation graph to different colors. Then, update the yellow part each iteration and update the red part (pivot point) every 100 epochs. An example can be found in `baselines/Reg_DOMD.py`.
